### ISSUE TITLE
UI Out of Sync - Simultaneous Updates

### ISSUE THREAD

**Issue by tgandrews** [ONSdigital/eq-author-app#316] opened 2019-04-15 10:50 UTC
### Expected behaviour
When updating multiple fields in separate updates against one entity then the updates should all be preserved in the UI.

### Steps to reproduce the behaviour
*Sometimes*
1. Update a field (e.g. page title) with a large amount of text
2. Click a button/toggle which also causes an update (e.g. optional fields toggle)
3. Then one of the updates is lost or the UI no longer reflects the state of the API.

### Technical information
When blurring a field an update is sent. Toggling a button also causes an update. 

By blurring a field and toggling a button in one action two updates to the one entity are sent in very quick succession (within ~12ms) this causes a race condition where depending on which response is received first can cause the apollo cache to either not reflect an update and no longer match the state of the API.

**Comment by pricea1** [comment] 2019-04-26 08:50
Possible solution but parked as can't reproduce error enough to test.
https://github.com/ONSdigital/eq-author-app/tree/1034-eq-author-app-316-ui-out-of-sync-simultaneous-updates-issue

**Comment by MattElcock** [comment] 2019-12-18 12:37
I'm also unable to reproduce this issue so I'll go ahead and close this.

**Closed by MattElcock** 2019-12-18 12:37 UTC
