### ISSUE TITLE
Moving a question referenced in a routing to after the reference crashes the app.

### ISSUE THREAD

**Issue by SamGodwin2** [ONSdigital/eq-author-app#280] opened 2019-03-25 11:20 UTC
### Expected behaviour
Given 2 sections each with a page and a number answer.
Make a routing rule on section 2 page 1 which references the answer in Section 1 page 1.
Move section 1 to after Section 2
The answer selector in the routing on Section 2 Page 1 should have the default `please select` selected.

### Actual behaviour
App crashes...

### Steps to reproduce the behaviour
See above

#### Browser
Chrome
#### Operating System
Mac

**Comment by jchapman68** [comment] 2019-05-01 14:51
Could not reproduce the error - maybe fixed as consequence of other changes.

**Comment by heofs** [comment] 2019-11-28 11:19
I could not reproduce this either, @SamGodwin2 can we close this?

**Comment by MattElcock** [comment] 2019-12-18 12:15
Closed as two devs couldn't reproduce the issue; @SamGodwin2 if you want this reopened let us know.

**Closed by MattElcock** 2019-12-18 12:15 UTC
