### ISSUE TITLE
View survey gives Error 500 on OSX

### ISSUE THREAD

**Issue by heofs** [ONSdigital/eq-author-app#348] opened 2019-05-17 08:51 UTC
### Expected behaviour
When clicking `View survey`, it should take you the the questionnaire in runner. And you should be able to start the questionnaire.

### Actual behaviour
When clicking view survey you get `Error 500`, and not being able see the questionnaire.

### Steps to reproduce the behaviour
Spin up the project and click `View survey`.

### Temporary fix
In `eq-author-app/eq-author-api/docker-compose.yml`, change this line
```PUBLISHER_URL=http://localhost:9000/publish/```
to
```PUBLISHER_URL=http://host.docker.internal:9000/publish/```

Update: From Docker version 18.03.0 it is recommended to use `host.docker.internal` instead of `docker.for.mac.localhost`. See https://docs.docker.com/docker-for-mac/release-notes/#docker-community-edition-18030-ce-mac59-2018-03-26

### Technical information
Docker Engine 28.09.2
Compose 1.23.2

#### Browser
Chrome 74

#### Operating System
OSX 10.14.4

### Screenshot
![Screenshot 2019-05-17 at 09 50 09](https://user-images.githubusercontent.com/11583422/57915879-a116f600-7889-11e9-8bca-9676e6dd1037.png)

**Comment by pricea1** [comment] 2019-07-11 13:08
This is dependant on how Survey runner is started. 

If started in Docker then the proposed change needs to be made.

If started locally as per Setup in https://github.com/ONSdigital/eq-survey-runner then existing config works.

Need to check with @samiwel which is the best approach.

**Comment by MattElcock** [comment] 2019-12-18 12:41
Unable to reproduce this so I'll go ahead and close it.

**Closed by MattElcock** 2019-12-18 12:41 UTC
